settings:
  transitionContextList:
   - push:
      color: "000000"
   - modal:
      color: "800080"
   - alert:
      color: "ef1609"
  defaulttransitionContext: push
  object:
   borderColor: .black
   contentColor: "00BFFF"
   textColor: "000000"
   verticalMargin: 16
   horizontalMargin: 100
   size:
    width: 100
    height: 50
  margin: 16
  imageName: "test.png"
  slashWidth: 3

views:
  - Splash:
      name: "スプラッシュ"
      views:
       - Hoge:
          name: "ほげ"
          transitionContext: modal
       - Hoge2:
          name: "ほげ2"
          transitionContext: modal
          views:
           - Hoge4:
              name: "ほげ40"
           - Hoge5:
              name: "ほげ50"
           - Hoge6:
              name: "ほげ60"
           - Hoge7:
              name: "ほげ70"
              views:
               - Hoge8:
                  name: "ほげ80"
       - Hoge3:
          name: "ほげ3"
          transitionContext: modal
          views:
           - Hoge4:
              name: "ほげ41"
           - Hoge5:
              name: "ほげ51"
  - LoginTop:
      name: "ログイントップ"
      transitionContext: modal
      views:
       - Hoge0:
          name: "ほげ"
       - Hoge:
          name: "ほげ"
       - Hoge2:
          name: "ほげ2"
          contentColor: "FFFFFF"
          views:
           - Hoge24:
              name: "ほげ24"
              views:
               - Hoge400:
                  name: "ほげ400"
               - Hoge401:
                  name: "ほげ401"
           - Hoge25:
              name: "ほげ25"
       - Hoge3:
          name: "ほげ3"
          views:
           - Hoge4:
              name: "ほげ34"
           - Hoge5:
              name: "ほげ35"
              views:
               - Hoge4:
                  name: "ほげ4"
                  views:
                   - Hoge6:
                      name: "ほげ6"
                      transitionContext: modal
                      views:
                        - Hoge7:
                           name: "ほげ7"
                           transitionContext: alert
                           contentColor: "FFFFFF"
                        - Hoge8:
                           name: "ほげ8"
                           transitionContext: alert
                        - Hoge9:
                           name: "ほげ9"
                        - Hoge10:
                           name: "ほげ10"
                        - Hoge11:
                           name: "ほげ11"
                        - Hoge12:
                           name: "ほげ12"
                        - Hoge13:
                           name: "ほげ13"
               - Hoge5:
                  name: "ほげ5"
  - LoginMail:
      name: "ログインメール"
  - Top:
      name: "トップ"
  - Detail:
      name: "詳細"
  - Setting:
      name: "設定"
  - Setting2:
      name: "設定2"
